name: build ebook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: sudo apt update
      - run: sudo apt install python3
      #- run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin
      - run: sudo apt-get install -y calibre
      # https://stackoverflow.com/questions/64211386/gitbook-cli-install-error-typeerror-cb-apply-is-not-a-function-inside-graceful
      # - run: sudo npm install graceful-fs@latest --save
      # - run: sudo npm install -g gitbook-cli
      # - run: gitbook install
      # gitbook replaced by https://github.com/honkit/honkit
      - run: npm install -g honkit
      # Compose books: https://honkit.netlify.app/ebook.html
      - run: mkdir output
      - run: honkit pdf ./ ./output/typescript-book-${SHA}.pdf
      - run: honkit epub ./ ./output/typescript-book-${SHA}.epub
      - run: honkit mobi ./ ./output/typescript-book-${SHA}.mobi
      - name: upload pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.pdf
          path: output/typescript-book-${{ env.SHA }}.pdf
      - name: upload epub artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.epub
          path: output/typescript-book-${{ env.SHA }}.epub
      - name: upload mobi artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.mobi
          path: output/typescript-book-${{ env.SHA }}.mobi
