name: build ebook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      # required for calibre installation
      - run: |
          sudo add-apt-repository ppa:apt-fast/stable
          sudo apt-get update
          sudo apt-get install -y apt-fast
          sudo apt-fast update
          sudo apt-fast install -y python3 calibre
      # gitbook replaced by https://github.com/honkit/honkit
      - run: |
          npm install -g honkit
          npm install -g gitbook-plugin-edit-link
          npm install -g gitbook-plugin-github
          npm install -g gitbook-plugin-header
      # Compose books: https://honkit.netlify.app/ebook.html
      - run: |
          mkdir output 
          npx honkit pdf ./ ./output/typescript-book-${SHA}.pdf
          npx honkit epub ./ ./output/typescript-book-${SHA}.epub
          npx honkit mobi ./ ./output/typescript-book-${SHA}.mobi
      - name: upload pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.pdf
          path: output/typescript-book-${{ env.SHA }}.pdf
      - name: upload epub artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.epub
          path: output/typescript-book-${{ env.SHA }}.epub
      - name: upload mobi artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-book.mobi
          path: output/typescript-book-${{ env.SHA }}.mobi
